name: Build C++ Screen Tricks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-wave:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build wave.cpp
        run: g++ wave.cpp -o wave.exe -lgdi32 -luser32 -mwindows -std=c++17

  build-triangulate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build triangulate.cpp
        run: g++ triangulate.cpp -o triangulate.exe -lgdi32 -luser32 -mwindows -std=c++17

  build-shuffle:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build shuffle.cpp
        run: g++ shuffle.cpp -o shuffle.exe -lgdi32 -luser32 -mwindows -std=c++17

  build-particles:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build particles.cpp
        run: g++ particles.cpp -o particles.exe -lgdi32 -luser32 -mwindows -std=c++17

  build-off:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build off.cpp
        run: g++ off.cpp -o off.exe -lgdi32 -lmsimg32 -mwindows -std=c++17
