name: Build C++ Screen Tricks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create build directory
        run: mkdir build

      - name: Build wave.cpp
        run: g++ wave.cpp -o build/wave.exe -lgdi32 -luser32 -mwindows -std=c++17

      - name: Build triangulate.cpp
        run: g++ triangulate.cpp -o build/triangulate.exe -lgdi32 -luser32 -mwindows -std=c++17

      - name: Build shuffle.cpp
        run: g++ shuffle.cpp -o build/shuffle.exe -lgdi32 -luser32 -mwindows -std=c++17

      - name: Build particles.cpp
        run: g++ particles.cpp -o build/particles.exe -lgdi32 -luser32 -mwindows -std=c++17

      - name: Build off.cpp
        run: g++ off.cpp -o build/off.exe -lgdi32 -lmsimg32 -mwindows -std=c++17

      - name: List executables
        run: dir build

      - name: Upload executables
        uses: actions/upload-artifact@v4
        with:
          name: cpp-builds
          path: build/
