name: Parallel C++ Build to Project Build Folder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-wave:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir build
      - run: g++ wave.cpp -o build/wave.exe -lgdi32 -luser32 -mwindows -std=c++17
      - uses: actions/upload-artifact@v4
        with:
          name: wave
          path: build/wave.exe

  build-triangulate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir build
      - run: g++ triangulate.cpp -o build/triangulate.exe -lgdi32 -luser32 -mwindows -std=c++17
      - uses: actions/upload-artifact@v4
        with:
          name: triangulate
          path: build/triangulate.exe

  build-shuffle:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir build
      - run: g++ shuffle.cpp -o build/shuffle.exe -lgdi32 -luser32 -mwindows -std=c++17
      - uses: actions/upload-artifact@v4
        with:
          name: shuffle
          path: build/shuffle.exe

  build-particles:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir build
      - run: g++ particles.cpp -o build/particles.exe -lgdi32 -luser32 -mwindows -std=c++17
      - uses: actions/upload-artifact@v4
        with:
          name: particles
          path: build/particles.exe

  build-off:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir build
      - run: g++ off.cpp -o build/off.exe -lgdi32 -lmsimg32 -mwindows -std=c++17
      - uses: actions/upload-artifact@v4
        with:
          name: off
          path: build/off.exe

  collect-builds:
    runs-on: ubuntu-latest
    needs: [build-wave, build-triangulate, build-shuffle, build-particles, build-off]
    steps:
      - uses: actions/checkout@v4
      - run: mkdir build
      - uses: actions/download-artifact@v4
        with:
          path: build
      - run: ls -R build
      - name: Commit build folder to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add build
          git commit -m "Add build outputs [skip ci]" || echo "No changes to commit"
          git push
